// Realistic-Python round-trip regression.
//
// The fixtures in tests/fixtures/realistic/ were generated by agents that had NO
// knowledge of BlockPy's parser — idiomatic OpenCV scripts and everyday Python programs.
// They guard against the parser regressing on real code (docstrings, f-strings, hex,
// kwargs, slicing, comprehensions, elif chains, multi-line literals, etc.).
//
// Pure Node test (no browser): parse(code) -> astToPython must equal the source modulo
// whitespace. One file (gen p09-style) intentionally exercises a redundant-parenthesis
// normalization that is semantically identical; see ALLOW_SEMANTIC below.
const { test, expect } = require('@playwright/test');
const fs = require('fs');
const path = require('path');
const P = require('../src/utils/parser.js');

const FIX_DIR = path.join(__dirname, 'fixtures', 'realistic');
const norm = (s) => s.replace(/\s+/g, '').trim();

// Files whose round-trip is semantically identical but not byte-exact (benign
// normalization such as dropping a redundant parenthesis around an aug-assign RHS).
// These still must PARSE and produce a STABLE (idempotent) round-trip.
const ALLOW_SEMANTIC = new Set(['p09.py']);

const files = fs.readdirSync(FIX_DIR).filter((f) => f.endsWith('.py')).sort();

test.describe('realistic Python round-trips losslessly', () => {
  for (const f of files) {
    test(`${f}`, () => {
      const code = fs.readFileSync(path.join(FIX_DIR, f), 'utf8');
      const out = P.astToPython(new P.Parser(new P.Tokenizer(code).tokenize()).parse());
      if (ALLOW_SEMANTIC.has(f)) {
        // Must parse and be stable under a second round-trip (no progressive loss).
        const out2 = P.astToPython(new P.Parser(new P.Tokenizer(out).tokenize()).parse());
        expect(norm(out2)).toBe(norm(out));
      } else {
        expect(norm(out)).toBe(norm(code));
      }
    });
  }
});
