/* pyAstBridge.js — CPython 3.12 ast (via Pyodide) <-> JSON IR. No hand-written parser.
 *
 * This is the foundation of the AST-IR redesign: Python text is parsed by the REAL
 * CPython ast.parse() running inside Pyodide and serialized to a canonical JSON IR
 * (node = { type: <ast.NodeName>, ...fields }). The inverse rebuilds ast nodes from
 * the IR and emits text via ast.unparse(). See DOCS/superpowers/specs/2026-06-07-*.
 *
 * Comments ARE preserved (Option 3: comments kept, formatting regenerated). Extraction uses
 * stdlib `tokenize` (NOT parso) to collect comments with positions, attaching them to statement
 * IR nodes as `_comments {leading[], trailing, after[]}` in `_parse`; `_unparse` re-emits them
 * via the `_CommentUnparser` subclass of `ast._Unparser`. Exact formatting (blank lines, quote
 * style) is regenerated by `ast.unparse`, not preserved byte-for-byte.
 *
 * Non-JSON Constant values (bytes / complex / Ellipsis / inf / nan) are valid CPython
 * 3.12 constants but are not JSON-serializable. To keep Python->IR total (raw=0 for
 * Constant), they are tagged as { "__py__": ... } leaves and decoded on the way back.
 * A primitive is never a plain dict, and AST nodes always carry "type", so a "__py__"
 * dict is unambiguous.
 */

// Serialize an ast tree to a JSON-able IR dict. Primitives are JSON-encoded (with
// non-JSON constants tagged); lists map; AST nodes become { type, <fields...>, _loc? }.
const PY_AST_TO_JSON = `
import ast, json, base64, tokenize, io
_SAFE_INT = 2**53 - 1  # JS Number.MAX_SAFE_INTEGER; ints beyond this lose precision in JSON.parse
def _enc_float(x):
    # inf / nan are not valid JSON tokens for the JS parser -> tag them. Also tag INTEGRAL-valued floats
    # (1.0, -0.0, 1e10): JS has no int/float distinction and JSON.stringify(1.0)=="1", so an untagged
    # integral float would silently round-trip back to an int (1.0 -> 1), breaking losslessness.
    if x != x or x in (float('inf'), float('-inf')) or x.is_integer():
        return {"__py__": "float", "repr": repr(x)}
    return x
def _enc_prim(v):
    if v is None or isinstance(v, bool) or isinstance(v, str):
        return v
    if isinstance(v, int):
        # large ints would be rounded by JS JSON.parse -> carry as a string
        return v if -_SAFE_INT <= v <= _SAFE_INT else {"__py__": "int", "s": str(v)}
    if isinstance(v, float):
        return _enc_float(v)
    if isinstance(v, bytes):
        return {"__py__": "bytes", "b64": base64.b64encode(v).decode('ascii')}
    if isinstance(v, complex):
        # real/imag may themselves be non-finite -> tag each through _enc_float
        return {"__py__": "complex", "real": _enc_float(v.real), "imag": _enc_float(v.imag)}
    if v is Ellipsis:
        return {"__py__": "ellipsis"}
    return v
# A field literally named "type" (only ExceptHandler in the closed 3.12 set) collides with
# the node-discriminator key, which is also "type". Remap such a field to "_field_type" in
# both directions so the discriminator and the field coexist losslessly.
def _key(f):
    return "_field_" + f if f == "type" else f
def _collect_comments(src):
    out = []
    lines = src.splitlines()
    try:
        for tok in tokenize.generate_tokens(io.StringIO(src).readline):
            if tok.type == tokenize.COMMENT:
                srow, scol = tok.start
                line = lines[srow - 1] if 0 <= srow - 1 < len(lines) else ''
                out.append({'line': srow, 'col': scol, 'text': tok.string,
                            'standalone': line[:scol].strip() == ''})
    except (tokenize.TokenError, IndentationError):
        pass  # ast.parse already succeeded; tokenize is best-effort on the same source
    return out
def _set_cmt(node, key, val, append):
    cm = getattr(node, '_cmt', None)
    if cm is None:
        cm = {}
        node._cmt = cm
    if append:
        cm.setdefault(key, []).append(val)
    else:
        cm[key] = val
def _attach_comments(tree, src):
    comments = _collect_comments(src)
    if not comments:
        return
    stmts = [n for n in ast.walk(tree) if isinstance(n, ast.stmt) and hasattr(n, 'lineno')]
    if not stmts:
        # comment-only module: nothing to anchor to -> carry on the Module node itself.
        for c in comments:
            _set_cmt(tree, 'leading', c['text'], True)
        return
    for c in comments:
        # 1) inline comment whose physical line falls within a statement's span -> trailing.
        #    Multiple inline comments on one multi-line statement accumulate (no overwrite).
        if not c['standalone']:
            span = [s for s in stmts if s.lineno <= c['line'] <= getattr(s, 'end_lineno', s.lineno)]
            if span:
                target = max(span, key=lambda s: (s.lineno, s.col_offset))
                cm = getattr(target, '_cmt', None) or {}
                prev = cm.get('trailing')
                _set_cmt(target, 'trailing', (prev + '  ' + c['text']) if prev else c['text'], False)
                continue
            # no span match (e.g. a decorator line) -> fall through to own-line placement below.
        # 2) standalone (or unanchored inline): attach to the next statement's leading, else to
        #    the nearest preceding statement's 'after'. Guarantees every comment lands on a node.
        after = [s for s in stmts if s.lineno > c['line']]
        if after:
            nxt = min(after, key=lambda s: s.lineno)
            if c['standalone'] and c['col'] > nxt.col_offset:
                # dangling end-of-block comment: attach to the last preceding deeper statement.
                before = [s for s in stmts if s.lineno < c['line'] and s.col_offset >= c['col']] \
                         or [s for s in stmts if s.lineno < c['line']]
                if before:
                    _set_cmt(max(before, key=lambda s: s.lineno), 'after', c['text'], True)
                else:
                    _set_cmt(nxt, 'leading', c['text'], True)
            else:
                _set_cmt(nxt, 'leading', c['text'], True)
        else:
            before = [s for s in stmts if s.lineno < c['line']]
            if before:
                _set_cmt(max(before, key=lambda s: s.lineno), 'after', c['text'], True)
            else:
                _set_cmt(stmts[0], 'leading', c['text'], True)
def _to_ir(node):
    if isinstance(node, ast.AST):
        d = {"type": type(node).__name__}
        for f in node._fields:
            d[_key(f)] = _to_ir(getattr(node, f, None))
        if hasattr(node, "lineno"):
            d["_loc"] = [node.lineno, getattr(node, "col_offset", 0)]
        if isinstance(node, ast.AST) and getattr(node, '_cmt', None):
            d["_comments"] = node._cmt
        return d
    if isinstance(node, list):
        return [_to_ir(x) for x in node]
    return _enc_prim(node)
def _parse(src):
    tree = ast.parse(src)
    _attach_comments(tree, src)
    return json.dumps(_to_ir(tree))
`;

// Rebuild ast nodes from the IR and unparse back to Python source.
const PY_IR_TO_CODE = `
import ast, json, base64
def _dec_num(x):
    # a complex component may itself be a tagged non-finite float
    if isinstance(x, dict) and x.get("__py__") == "float":
        return float(x["repr"])
    return x
def _dec_prim(d):
    t = d["__py__"]
    if t == "int":     return int(d["s"])
    if t == "bytes":   return base64.b64decode(d["b64"])
    if t == "complex": return complex(_dec_num(d["real"]), _dec_num(d["imag"]))
    if t == "ellipsis": return Ellipsis
    if t == "float":   return float(d["repr"])  # 'inf' / '-inf' / 'nan'
    raise ValueError("unknown __py__ tag: " + str(t))
def _key(f):
    return "_field_" + f if f == "type" else f
def _from_ir(d):
    if isinstance(d, dict) and "type" in d:
        cls = getattr(ast, d["type"])
        kwargs = {f: _from_ir(d.get(_key(f))) for f in cls._fields}
        node = ast.fix_missing_locations(cls(**kwargs))
        if d.get("_comments"):
            node._cmt = d["_comments"]
        return node
    if isinstance(d, dict) and "__py__" in d:
        return _dec_prim(d)
    if isinstance(d, list):
        return [_from_ir(x) for x in d]
    return d

class _CommentUnparser(ast._Unparser):
    # Re-injects extracted comments with ZERO loss. Three comment kinds per stmt node
    # (carried on node._cmt): leading (own line(s) before, at stmt indent), trailing
    # (appended to the END of the stmt's HEADER line), after (own line(s) after, at
    # stmt indent). The base _Unparser emits some statements WITHOUT calling traverse
    # (elif-collapse in visit_If; the docstring stmt in _write_docstring_and_traverse_body),
    # so those bypasses are handled explicitly below. A node reached via traverse must NOT
    # also be emitted by a visit_* / docstring override -> no double-emission.
    # Trailing placement is two-staged to land on the HEADER line of a compound stmt:
    #   _armed_trailing   -> a trailing comment for the stmt currently being entered; it is
    #                        promoted to _pending_trailing by the FIRST fill() of that stmt
    #                        (every ast.stmt visitor in _Unparser starts with fill()), i.e.
    #                        once its header line has been opened and AFTER any leading lines.
    #   _pending_trailing -> a comment to append at the END of the current line, flushed by
    #                        maybe_newline() just before the newline that closes the line.
    # This two-stage hop is what stops a trailing comment from latching onto a leading
    # comment line, and what keeps it on the for/if/def header rather than the last body line.
    def __init__(self, *a, **k):
        super().__init__(*a, **k)
        self._pending_trailing = None
        self._armed_trailing = None
    def maybe_newline(self):
        if self._pending_trailing is not None:
            t = self._pending_trailing
            self._pending_trailing = None
            self.write('  ' + t)
        super().maybe_newline()
    def fill(self, text=''):
        super().fill(text)
        # The first fill() after arming opens the stmt's header line -> promote to pending so
        # the NEXT maybe_newline appends the trailing to the end of THIS header line.
        if self._armed_trailing is not None:
            self._pending_trailing = self._armed_trailing
            self._armed_trailing = None
    def _emit_leading(self, node):
        cm = getattr(node, '_cmt', None)
        if cm:
            for lead in cm.get('leading', []):
                self.fill(lead)
    def _arm_trailing(self, node):
        cm = getattr(node, '_cmt', None)
        if cm and cm.get('trailing'):
            self._armed_trailing = cm['trailing']
    def _emit_after(self, node):
        cm = getattr(node, '_cmt', None)
        if cm:
            for aft in cm.get('after', []):
                self.fill(aft)
    def visit_Module(self, node):
        # The Module node itself can carry comments (comment-only module, or a dangling
        # 'after' at end of file) — it is not reached via traverse, so emit here.
        self._emit_leading(node)
        super().visit_Module(node)
        self._emit_after(node)
    def traverse(self, node):
        # Per-statement comment emission for everything reached via traverse (the common path).
        if isinstance(node, ast.stmt):
            self._emit_leading(node)
            self._arm_trailing(node)       # promoted on the stmt's own first fill()
            super().traverse(node)
            self._emit_after(node)
        else:
            super().traverse(node)
    def _write_docstring_and_traverse_body(self, node):
        # Base impl emits node.body[0] (the docstring Expr) via _write_docstring, bypassing
        # traverse -> its comments would be lost. Emit them here; body[1:] still goes through
        # traverse normally (no double-emission of the docstring stmt or the rest of the body).
        if (docstring := self.get_raw_docstring(node)):
            doc_stmt = node.body[0]
            self._emit_leading(doc_stmt)
            self._arm_trailing(doc_stmt)   # _write_docstring's fill() promotes it to the doc line
            self._write_docstring(docstring)
            self._emit_after(doc_stmt)
            self.traverse(node.body[1:])
        else:
            self.traverse(node.body)
    def visit_If(self, node):
        # Mirrors 3.12 _Unparser.visit_If (elif-collapse), but emits the comments of each
        # collapsed nested If. The TOP If is reached via traverse, so its leading/trailing/
        # after are already handled by the traverse override -> do NOT re-emit them here.
        self.fill('if ')
        self.traverse(node.test)
        with self.block():
            self.traverse(node.body)
        # collapse nested ifs into equivalent elifs.
        while node.orelse and len(node.orelse) == 1 and isinstance(node.orelse[0], ast.If):
            node = node.orelse[0]
            self._emit_leading(node)        # leading on its own line(s) before the elif line
            self._arm_trailing(node)        # promoted by the fill('elif ') below -> lands on elif line
            self.fill('elif ')
            self.traverse(node.test)
            with self.block():
                self.traverse(node.body)
            self._emit_after(node)          # dangling after the elif's body, at if-indent
        # final else
        if node.orelse:
            self.fill('else')
            with self.block():
                self.traverse(node.orelse)

def _unparse(js):
    up = _CommentUnparser()
    out = up.visit(_from_ir(json.loads(js)))
    # A trailing comment on the LAST statement has no following newline to trigger the flush
    # in maybe_newline -> append whatever is still buffered so it is never lost.
    tail = up._pending_trailing if up._pending_trailing is not None else up._armed_trailing
    if tail is not None:
        out = out + '  ' + tail
    return out
`;

async function pythonToIR(pyodide, code) {
  pyodide.runPython(PY_AST_TO_JSON);
  // _parse is a PyProxy; release it after use so repeated sync doesn't leak WASM resources.
  const parse = pyodide.globals.get('_parse');
  try {
    return JSON.parse(parse(code));
  } finally {
    parse.destroy();
  }
}

async function irToPython(pyodide, ir) {
  pyodide.runPython(PY_IR_TO_CODE);
  const unparse = pyodide.globals.get('_unparse');
  try {
    return unparse(JSON.stringify(ir));
  } finally {
    unparse.destroy();
  }
}

// Resolve the live Pyodide instance for the conversion path. Prefer the readiness promise: it
// resolves only after FULL init (micropip + builtins), so awaiting it avoids racing a runPython
// against in-flight setup (window.__pyodide is set mid-init, before setup completes). Awaiting an
// already-resolved promise is immediate. Fall back to the live handle only when no promise exists
// (e.g. a runtime injected directly). Throws if Pyodide was never initialized.
async function getPyodide() {
  if (typeof window === 'undefined') throw new Error('getPyodide: no window');
  if (window.__pyodideReadyPromise) return window.__pyodideReadyPromise;
  if (window.__pyodide) return window.__pyodide;
  throw new Error('getPyodide: Pyodide not initialized (initPyodide/prewarmEnvironment must run first)');
}

const BlockPyAstBridge = { pythonToIR, irToPython, getPyodide, PY_AST_TO_JSON, PY_IR_TO_CODE };
if (typeof window !== 'undefined') window.BlockPyAstBridge = BlockPyAstBridge;
if (typeof module !== 'undefined') module.exports = BlockPyAstBridge;
